import type { components as RawComponents } from "./schema";

/**
 * Thin typed aliases over the OpenAPI-generated schema (doc 35.2).
 *
 * The canonical types live in `schema.d.ts`, generated by
 * `openapi-typescript` from the backend's `/openapi.json`. These aliases
 * give the app named, stable references without hand-maintaining a second
 * copy of the backend contract.
 */
type Components = RawComponents["schemas"];

export type ApiRun = Components["Run"];
export type ApiRunCreate = Components["RunCreate"];
export type ApiRunUpdate = Components["RunUpdate"];
export type ApiTaskCreate = Components["TaskCreate"];
export type ApiTaskUpdate = Components["TaskUpdate"];
export type ApiMessageCreate = Components["MessageCreate"];
export type ApiSandboxStart = Components["SandboxStart"];
export type ApiApprovalView = Components["ApprovalView"];
export type ApiApprovalResolve = Components["ApprovalResolve"];
export type ApiArtifactUpdate = Components["ArtifactUpdate"];
export type ApiSettings = Components["Settings"];
export type ApiFileWrite = Components["FileWrite"];
export type ApiFilePatch = Components["FilePatch"];
export type ApiFileCreate = Components["FileCreate"];
export type ApiPaperUpdate = Components["PaperUpdate"];
