import type { components as RawComponents } from "./schema";

/**
 * Thin typed aliases over the OpenAPI-generated schema.
 *
 * The canonical types live in `schema.d.ts`, generated by
 * `openapi-typescript` from the backend's `/openapi.json`. These aliases
 * give the app named, stable references without hand-maintaining a second
 * copy of the backend contract.
 */
type Components = RawComponents["schemas"];

export type ApiRun = Components["Run"];
export type ApiRunCreate = Components["RunCreate"];
export type ApiRunUpdate = Components["RunUpdate"];
export type ApiTask = Components["TaskCreate"];
export type ApiTaskCreate = Components["TaskCreate"];
export type ApiTaskUpdate = Components["TaskUpdate"];
export type ApiMessage = Components["MessageCreate"];
export type ApiMessageCreate = Components["MessageCreate"];
export type ApiSandbox = {
  id: string;
  run_id?: string;
  container_id?: string;
  app_path?: string;
  preview_port?: number;
  status?: string;
  environment?: string;
  preview_url?: string | null;
  error?: string | null;
  started_at?: string;
  stopped_at?: string;
};
export type ApiSandboxStart = Components["SandboxStart"] & ApiSandbox;
export type ApiApproval = Components["ApprovalView"];
export type ApiApprovalView = Components["ApprovalView"];
export type ApiApprovalResolve = Components["ApprovalResolve"];
export type ApiArtifact = Components["ArtifactUpdate"];
export type ApiArtifactUpdate = Components["ArtifactUpdate"];
export type ApiPaper = {
  paper_id: string;
  title: string;
  pdf_path: string;
  status: string;
  created_at?: string;
  parsed_at?: string;
  card_path?: string | null;
};
export type ApiPaperUpdate = Components["PaperUpdate"];
export type ApiFileWrite = Components["FileWrite"];
export type ApiFilePatch = Components["FilePatch"];
export type ApiFileCreate = Components["FileCreate"];
export type ApiSettings = Components["Settings"];
